### ISSUE TITLE
[Documentation] Typo in example for CIlogon section in the callback URLs bullet

### ISSUE THREAD

**Issue by ncase2** [SAGE-3/next#1019]
I tried clicking "Edit this page" to see if I could update it myself to no avail so I thought I'd post here. Please delete if this is not the right place/format!

Link to section:
[https://sage-3.github.io/docs/Server-Deployment#cilogon](https://sage-3.github.io/docs/Server-Deployment#cilogon)
> * Callback URLs: To ensure CILogon redirects back to the SAGE3 server after the user logins, postfix your server URL with: /auth/cilogon/redirect. (Ex. https://sage3.manoa.hawaii.edu/auth/cilogon.redirect)

`cilogon.redirect` should be updated to `cilogon/redirect`

Minor issue, but I used the example to make request the CI Logon and had to have them update the `.` to `/` to get it to work. 

Also, I was having issues until I upgraded from 1.2 to 1.3, maybe we could have the docs start with 1.3? 

Happy to make the changes if you all can direct me what to edit! I was able to successfully set up my own server following the instructions and making the above changes. Thank you for your time and effort!

**Comment by renambot-uic** [comment]
]
] Minor issue, but I used the example to make request the CI Logon and had to have them update the . to / to get it to work.
] 

Thanks, fixed.

] maybe we could have the docs start with 1.3?

Indeed, we need to update that document.
