### ISSUE TITLE
PresenceFollow behaviour: is it intended that actions within applications are not followed

### ISSUE THREAD

**Issue by ipeakermit** [SAGE-3/next#674]
I am able to replicate the PresenceFollow feature. However in my testing, actions such as key or mouse events pertaining to specific applications (such as inside a specific WebView) are not followed. Is that the intended behaviour?

**Comment by rctheriot** [comment]
I'm assuming the intended behavior is similar to SAGE2 cursors. 

From your laptop you take control of the cursor on the display wall's computer, and your IO events are sent from your laptop to the wall.
